[package]
name = "input_lang_get_icon"
version = "0.1.0"
authors = ["NightMachinary <rudiwillalwaysloveyou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd_lib = "0.8.5"
dirs = "3.0.1"
